version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/Dockerfile
    container_name: api
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - mysql
    environment:
      - MONGO_URL=mongodb://mongo:27017/moveekdb
      - MYSQL_URL=mysql://root:123456@mysql:3306/moveekdb
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=moveekdb

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: moveekdb
      MYSQL_USER: moveek
      MYSQL_PASSWORD: 12345678

volumes:
  mongo_data:
  mysql_data:
