export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  BRAND_MANAGER = 'BRAND_MANAGER',
  CINEMA_MANAGER = 'CINEMA_MANAGER',
  COUNTER_STAFF = 'COUNTER_STAFF',
  USER = 'USER',
  REVIEWER = 'REVIEWER',
}
